// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:1
/*
   This Source Code Form is subject to the terms of the Mozilla Public
   License, v. 2.0. If a copy of the MPL was not distributed with this
   file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

package parser

import __yyfmt__ "fmt"

//line parser.y:8

//line parser.y:11
type yySymType struct {
	yys int
	v   Value
}

const TOKEN_WHILE = 57346
const TOKEN_IF = 57347
const TOKEN_ELSE = 57348
const TOKEN_IDENTIFIER = 57349
const TOKEN_NUMBER = 57350
const TOKEN_STRING = 57351
const TOKEN_OPERATOR = 57352
const TOKEN_COMMA = 57353
const TOKEN_EQUAL = 57354
const TOKEN_OPEN_PAR = 57355
const TOKEN_CLOSE_PAR = 57356
const TOKEN_OPEN_CURL = 57357
const TOKEN_CLOSE_CURL = 57358
const TOKEN_OPEN_BRAC = 57359
const TOKEN_CLOSE_BRAC = 57360

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TOKEN_WHILE",
	"TOKEN_IF",
	"TOKEN_ELSE",
	"TOKEN_IDENTIFIER",
	"TOKEN_NUMBER",
	"TOKEN_STRING",
	"TOKEN_OPERATOR",
	"TOKEN_COMMA",
	"TOKEN_EQUAL",
	"TOKEN_OPEN_PAR",
	"TOKEN_CLOSE_PAR",
	"TOKEN_OPEN_CURL",
	"TOKEN_CLOSE_CURL",
	"TOKEN_OPEN_BRAC",
	"TOKEN_CLOSE_BRAC",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:64

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 44

var yyAct = [...]int{

	13, 7, 31, 6, 10, 9, 10, 22, 8, 30,
	12, 16, 11, 18, 11, 23, 11, 25, 24, 14,
	15, 20, 27, 28, 9, 10, 2, 8, 22, 21,
	29, 33, 34, 32, 26, 11, 14, 15, 17, 19,
	5, 4, 3, 1,
}
var yyPact = [...]int{

	-1000, -1000, 20, -1000, -1000, -1000, -1000, -1000, -2, 29,
	29, -1000, 12, -3, -1000, -1000, -3, 1, 18, -1000,
	-1000, 29, 29, -1000, 24, -1000, -9, 18, -1000, -1,
	-1000, 29, -1000, -1000, 18,
}
var yyPgo = [...]int{

	0, 43, 26, 1, 42, 41, 40, 3, 0, 39,
	34,
}
var yyR1 = [...]int{

	0, 1, 3, 2, 2, 4, 4, 4, 4, 7,
	7, 7, 5, 5, 8, 8, 8, 6, 9, 9,
	10, 10,
}
var yyR2 = [...]int{

	0, 1, 3, 0, 2, 1, 1, 1, 1, 3,
	5, 5, 3, 3, 1, 1, 3, 3, 1, 3,
	1, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, -4, -5, -6, -7, -3, 7, 4,
	5, 15, 12, -8, 7, 8, -8, -2, -8, -9,
	9, 17, 10, -3, -3, 16, -10, -8, -8, 6,
	18, 11, -7, -3, -8,
}
var yyDef = [...]int{

	3, -2, 1, 4, 5, 6, 7, 8, 0, 0,
	0, 3, 0, 0, 14, 15, 0, 0, 12, 13,
	18, 0, 0, 17, 9, 2, 0, 20, 16, 0,
	19, 0, 10, 11, 21,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:23
		{
			yylex.(*Lexer).parseResult = yyDollar[1].v
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:26
		{
			yyVAL.v = yyDollar[2]
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line parser.y:29
		{
			yyVAL.v = &block{}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line parser.y:30
		{
			yyDollar[1].v.(*block).push(yyDollar[2].v)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:33
		{
			yyVAL.v = yyDollar[1].v
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:34
		{
			yyVAL.v = yyDollar[1].v
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:35
		{
			yyVAL.v = yyDollar[1].v
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:36
		{
			yyVAL.v = yyDollar[1].v
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:39
		{
			yyVAL.v = &condStmt{yyDollar[1].v, yyDollar[2].v, nil}
		}
	case 10:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line parser.y:40
		{
			yyVAL.v = &condStmt{yyDollar[1].v, yyDollar[2].v, yyDollar[3].v}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:44
		{
			yyVAL.v = &assignment{yyDollar[1].v.(string), yyDollar[3].v}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:45
		{
			yyVAL.v = &assignment{yyDollar[1].v.(string), yyDollar[3].v}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:48
		{
			yyVAL.v = yyDollar[1].v
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:49
		{
			yyVAL.v = yyDollar[1].v
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:50
		{
			yyVAL.v = yyDollar[1].v
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:56
		{
			yyVAL.v = yyDollar[1].v
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:57
		{
			yyVAL.v = yyDollar[2].v
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line parser.y:60
		{
			yyVAL.v = []Value{yyDollar[1].v}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line parser.y:61
		{
			yyVAL.v = append(yyDollar[1].v.([]Value), yyDollar[3].v)
		}
	}
	goto yystack /* stack new state and value */
}
